// <auto-generated />
namespace FoodCo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class block1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(block1));
        
        string IMigrationMetadata.Id
        {
            get { return "202410231749166_block1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
